version: "3"
services:
  app:
    image: todo-app
    container_name: todo-app
    ports:
      - "9090:9090"
  front:
    image: todo-front
    container_name: todo-front
    ports:
      - "8080:8080"
    depends_on:
      - app