version: "3"
services:
  app:
    image: todo-list
    container_name: todo-list-app
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: mysql
    container_name: todo-list-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${path}:/var/lib/mysql